import { FieldDefinition, Language } from './types';

const en: Record<string, string> = {
  company_name: 'What is the name of your company?',
  business_registration_number: 'What is your business registration number?',
  address: 'What is your company address (city/region)?',
  mobile_number: 'What is your mobile number (in +251 format)?',
  email: 'What is your email address? (Optional)',
  business_organization_form: 'What is your business organization form? (Sole Proprietorship, Private Limited Company, Share Company, or Other)',
  years_in_operation: 'How many years has your business been operating?',
  business_type: 'What is your business type/sector? (e.g., textile, leather, service, metal, agriculture)',
  ownership_percentage_women: 'What percentage of the company is owned by women?',
  ownership_percentage_men: 'What percentage of the company is owned by men?',
  development_since_start: 'Please describe the development of your business since it started.',
  motivation_to_apply: 'What is your motivation to apply? (Max 150 words)',
  business_goals: 'What are your business goals? (Max 100 words)',
  market_overview: 'Please provide a market overview for your business.',
  product_service_1: 'What is your main product/service?',
  market_served_1: 'What market does this product/service serve?',
  distribution_channels_1: 'What are the distribution channels for this product/service?',
  product_service_uniqueness: 'What makes your product/service unique?',
  raw_material_sourcing_pct: 'What percentage of raw materials are locally sourced?',
  management_name_1: 'What is the name of a core management team member?',
  management_position_1: 'What is their position?',
  management_gender_1: 'What is their gender?',
  problem_to_be_addressed: 'What problem are you trying to address with this intervention?',
  machinery_description_1: 'What equipment do you need?',
  machinery_quantity_1: 'How many units?',
  machinery_price_1: 'What is the estimated total price in ETB?',
  machinery_purpose_1: 'What is the purpose of this equipment?',
  consultant_problem_1: 'What problem requires technical expertise?',
  consultant_expertise_1: 'What technical expertise is needed?',
  expected_results: 'What are the expected results from this intervention?',
  priority_area_1: 'How does the machinery/expert support achieve the expected results? (Priority 1)',
  priority_area_2: 'How does the machinery/expert support achieve the expected results? (Priority 2)',
  priority_area_3: 'How does the machinery/expert support achieve the expected results? (Priority 3)',
  job_creation_explanation: 'How many jobs will be created over the next 15 months? Please explain.',
  job_position_1: 'What is the job position?',
  job_count_1: 'How many new jobs for this position?',
  social_env_impact_osh: 'What is the social/environmental impact and OHS? (Max 100 words)',
  osh_standards: 'What occupational safety and health standards do you follow? (Max 100 words)',
};

const am: Record<string, string> = {
  company_name: 'የኩባንያዎ ስም ማን ይባላል?',
  business_registration_number: 'የንግድ ምዝገባ ቁጥርዎ ስንት ነው?',
  address: 'የኩባንያዎ አድራሻ (ከተማ/ክልል) ማን ይባላል?',
  mobile_number: 'የስልክ ቁጥርዎ ስንት ነው (+251 ቅርጸት)?',
  email: 'ኢሜይል አድራሻዎ ማን ይባላል? (አማራጭ)',
  business_organization_form: 'የንግድ ድርጅት ቅርጸት ምንድን ነው? (የአንድ ሰው ማህበረሰብ፣ የግል የተገደበ ኩባንያ፣ የአክሲዮን ኩባንያ፣ ወይም ሌላ)',
  years_in_operation: 'ንግድዎ ስንት ዓመት ነው በሚሰራበት?',
  business_type: 'የንግድ ዓይነት/ዘዴ ምንድን ነው? (ለምሳሌ የነሽቱ ጥበብ፣ ብርጭቆ፣ አገልግሎት፣ መቱ፣ የህብረት)',
  ownership_percentage_women: 'የኩባንያው ባለቤትነት ሴቶች ስንት በመቶ ነው?',
  ownership_percentage_men: 'የኩባንያው ባለቤትነት ወንዶች ስንት በመቶ ነው?',
  development_since_start: 'ከጀምሩ ጀምሮ የንግድዎን እድገት ያብርቱ።',
  motivation_to_apply: 'ለመመዝገብ ምንድን ነው አስተሳሰብዎ? (በስድስት ቃላት ውስጥ)',
  business_goals: 'የንግድ ግብዣዎች ምንድን ናቸው? (በዘጠኝ ቃላት ውስጥ)',
  market_overview: 'ለንግድዎ የማርኬት አጠቃላይ ሁኔታ ያብርቱ።',
  product_service_1: 'ዋናው ምርት/አገልግሎትዎ ምንድን ነው?',
  market_served_1: 'ይህ ምርት/አገልግሎት ማንን አገልግሎታል?',
  distribution_channels_1: 'የዚህ ምርት/አገልግሎት የማከማቻ አካባቢዎች ምንድን ናቸው?',
  product_service_uniqueness: 'ምርት/አገልግሎትዎ ምን ያስፈልጋል?',
  raw_material_sourcing_pct: 'የጠላማ ቁልፍ ስርዓት ስንት በመቶ ነው ከውስጥ የሚገኙ?',
  management_name_1: 'የዋናው አስተዳደር ቡድን አባል ስም ማን ይባላል?',
  management_position_1: 'የቱንም ሚና አለው?',
  management_gender_1: 'ፆታው ምንድን ነው?',
  problem_to_be_addressed: 'ከዚህ ስልት ጋር የሚፈታደር ሽታ ምንድን ነው?',
  machinery_description_1: 'ምን ዕቃዎች አስፈላጊ ናቸው?',
  machinery_quantity_1: 'ስንት አካል?',
  machinery_price_1: 'የሚጠበቀው ጠቅላላ ዋጋ በኢትብ ስንት ነው?',
  machinery_purpose_1: 'የዚህ ዕቃ ለምን ነው?',
  consultant_problem_1: 'የትኛው ሽታ የቴክኒካል እባክነትን ያስፈልጋል?',
  consultant_expertise_1: 'የትኛው ቴክኒካል እባክነት ያስፈልጋል?',
  expected_results: 'ከዚህ ስልት የሚገባ የሚጠበቁ ውጤቶች ምንድን ናቸው?',
  priority_area_1: 'ዕቃዎችን/እባክነት እንዴት ነው የሚጠበቁ ውጤቶችን ለማስፈጸም ያስችላሉ? (ቅድሚያ 1)',
  priority_area_2: 'ዕቃዎችን/እባክነት እንዴት ነው የሚጠበቁ ውጤቶችን ለማስፈጸም ያስችላሉ? (ቅድሚያ 2)',
  priority_area_3: 'ዕቃዎችን/እባክነት እንዴት ነው የሚጠበቁ ውጤቶችን ለማስፈጸም ያስችላሉ? (ቅድሚያ 3)',
  job_creation_explanation: 'በሚቀጥለው 15 ወር ውስጥ ስንት ሰራተኛ ይፈጠራል? እባክዎ ያብርቱ።',
  job_position_1: 'የሰራተኛ ሚና ምንድን ነው?',
  job_count_1: 'ለዚህ ሚና ስንት አዲስ ሰራተኞች?',
  social_env_impact_osh: 'ማህበራዊ/አካባቢያዊ ተብሎምና የሰራተኛ ደህንነት ምንድን ነው? (በዘጠኝ ቃላት ውስጥ)',
  osh_standards: 'የትኛው የሰራተኛ ደህንነት ወሰን ነው የሚከተሉት? (በዘጠኝ ቃላት ውስጥ)',
};

const om: Record<string, string> = {
  company_name: 'Maqaa kaampaaniyaa keessanii maali?',
  business_registration_number: 'Lakkoofsi galmee daldalaa keessanii meeqa?',
  address: 'Teessoo kaampaaniyaa keessanii (magaalaa/kilil) eessa?',
  mobile_number: 'Lakkoofsi bilbilaa keessanii meeqa? (+251)',
  email: 'Imeelii keessanii maali? (Waliigalaa)',
  business_organization_form: 'Hojii daldalaa keessanii qabaa qaabni maali? (Kan of eegaa, kan biroo gahaa, kan akishiyoonii, knoo waliin)',
  years_in_operation: 'Daldalaa keessan waggaa meeqa tajaajilaa jira?',
  business_type: 'Qabaa daldalaa keessanii maali? (fkn: eeggii, lika, tajaajila, cinii, hojii qotee)',
  ownership_percentage_women: 'Kaampaaniyaatti dubartoonni qabiyyeen keenya meeqa?',
  ownership_percentage_men: 'Kaampaaniyaatti dhirachoonni qabiyyeen keenya meeqa?',
  development_since_start: 'Jalqabee irraa daldalaa keessanii dandaama qabsaa\'u deeggarsa.',
  motivation_to_apply: 'Galmee\'uuf barbaaddaa kee maali? (Saasa 150 irratti)',
  business_goals: 'Kaayyoo daldalaa keessan maali? (Saasa 100 irratti)',
  market_overview: 'Daldalaa keessanii gabaabaa garaagaraa deeggarsa.',
  product_service_1: 'Mootummaa/tajaajila guddaa keessan maali?',
  market_served_1: 'Kun mootummaa/tajaajila maatii tajaajilluu danda\'a?',
  distribution_channels_1: 'Kan mootummaa/tajaajilaa kaayyoo gurgurtoo maali?',
  product_service_uniqueness: 'Mootummaa/tajaajilaa keessan maaliif qabxii qaba?',
  raw_material_sourcing_pct: 'Qabiyyeen biyya keessaa jiru qabiin filannoo meeqa?',
  management_name_1: 'Maqaa lammaa hojii maatii/bulchiinsaa guddaa kanneen maali?',
  management_position_1: 'Hoji isaa maali?',
  management_gender_1: 'Saala isaa maali?',
  problem_to_be_addressed: 'Kun hojii irraa yoo dhufu yoo ta\'u rakkachi maali qabate?',
  machinery_description_1: 'Meeshaa qaaboo meeqa barbaachisaa dha?',
  machinery_quantity_1: 'Meessni meeqa?',
  machinery_price_1: 'Qimmii waliigalaa irratti ETB meeqa?',
  machinery_purpose_1: 'Kun meeshaa maaliif?',
  consultant_problem_1: 'Rakkachi qabxii kan teknikoolaa barbaachisaa dha?',
  consultant_expertise_1: 'Barbaachisa teknikoolaa meeqa qabate?',
  expected_results: 'Kun hojii irraa gaarii kan tarree jira maali?',
  priority_area_1: 'Meeshaalee/barbaachisaa teknikoolaa gaariiwwan kun akka danda\'amuuf dandaa\'u? (Olaanaa 1)',
  priority_area_2: 'Meeshaalee/barbaachisaa teknikoolaa gaariiwwan kun akka danda\'amuuf dandaa\'u? (Olaanaa 2)',
  priority_area_3: 'Meeshaalee/barbaachisaa teknikoolaa gaariiwwan kun akka danda\'amuuf dandaa\'u? (Olaanaa 3)',
  job_creation_explanation: 'Waggaa 15 keessaa hojjettoota meeqa dabalataan jira? Ibsu.',
  job_position_1: 'Hojii maali?',
  job_count_1: 'Kun hojii irratti hojjettoota haaraa meeqa?',
  social_env_impact_osh: 'Danda\'a waldaa/aanaa fi hojii nagaa maali? (Saasa 100 irratti)',
  osh_standards: 'Qaabiyyeessa nagaa hojjettootaa fi fayyaa maali qabate? (Saasa 100 irratti)',
};

const followUpEn: Record<string, string> = {
  company_name: 'Could you please repeat the company name?',
  business_registration_number: 'The registration number seems incomplete. Could you provide the full number?',
  address: 'Please provide the full address including city and region.',
  mobile_number: 'Please provide a valid Ethiopian mobile number starting with +251.',
  business_organization_form: 'Please specify: Sole Proprietorship, Private Limited Company, Share Company, or Other.',
  years_in_operation: 'Please provide a numeric value for years in operation.',
  business_type: 'Please specify the sector (e.g., textile, leather, service, metal, agriculture).',
  ownership_percentage_women: 'Please provide a percentage between 0 and 100.',
  ownership_percentage_men: 'Please provide a percentage between 0 and 100. The total should sum to 100% with women\'s percentage.',
  development_since_start: 'Please provide more details about your business development.',
  motivation_to_apply: 'Please keep your motivation under 150 words.',
  business_goals: 'Please keep your business goals under 100 words.',
  market_overview: 'Please provide more details about your market.',
  product_service_1: 'Please describe your main product/service.',
  market_served_1: 'Please specify the market (local, national, international).',
  distribution_channels_1: 'Please describe your distribution channels.',
  product_service_uniqueness: 'What makes your product/service different from competitors?',
  raw_material_sourcing_pct: 'Please provide a percentage between 0 and 100.',
  management_name_1: 'Please provide the name of the management team member.',
  management_position_1: 'Please provide their position.',
  management_gender_1: 'Please specify gender (Male/Female/Other).',
  problem_to_be_addressed: 'Please describe the specific problem.',
  machinery_description_1: 'Please describe the equipment needed.',
  machinery_quantity_1: 'Please provide a numeric quantity.',
  machinery_price_1: 'Please provide the estimated total price in ETB.',
  machinery_purpose_1: 'Please explain the purpose of this equipment.',
  consultant_problem_1: 'Please describe the problem requiring expertise.',
  consultant_expertise_1: 'Please specify the technical expertise needed.',
  expected_results: 'Please describe the expected results.',
  priority_area_1: 'Please explain how the support achieves the results.',
  priority_area_2: 'Please explain how the support achieves the results.',
  priority_area_3: 'Please explain how the support achieves the results.',
  job_creation_explanation: 'Please provide the number of jobs and explanation.',
  job_position_1: 'Please specify the job position.',
  job_count_1: 'Please provide a numeric value for new jobs.',
  social_env_impact_osh: 'Please keep under 100 words.',
  osh_standards: 'Please keep under 100 words.',
};

const followUpAm: Record<string, string> = {
  company_name: 'እባክዎ የኩባንያውን ስም ደግሞ ያብርቱ?',
  business_registration_number: 'የምዝገባ ቁጥር የተለዋዋ ይመስላል። እባክዎ ሙሉውን ቁጥር ያብርቱ?',
  address: 'እባክዎ ከተማ እና ክልል ጋር ሙሉ አድራሻውን ያብርቱ።',
  mobile_number: 'እባክዎ +251 የሚጀምር የተጠቃሚ የኢትዮጵያ ስልክ ቁጥር ያብርቱ።',
  business_organization_form: 'እባክዎ ይጠቀሱ: የአንድ ሰው ማህበረሰብ፣ የግል የተገደበ ኩባንያ፣ የአክሲዮን ኩባንያ፣ ወይም ሌላ።',
  years_in_operation: 'እባክዎ ለዓመታት ቁጥር ያብርቱ።',
  business_type: 'እባክዎ ዘዴውን ያብርቱ (ለምሳሌ የነሽቱ ጥበብ፣ ብርጭቆ፣ አገልግሎት፣ መቱ፣ የህብረት)።',
  ownership_percentage_women: 'እባክዎ ከ 0 እስከ 100 የሚሆን በመቶ ያብርቱ።',
  ownership_percentage_men: 'እባክዎ ከ 0 እስከ 100 የሚሆን በመቶ ያብርቱ። የሴቶች በመቶ ጋር ጠቅላላው 100% ሊሆን አለበት።',
  development_since_start: 'እባክዎ ተጨማሪ ዝርዝር ያብርቱ።',
  motivation_to_apply: 'እባክዎ አስተሳሰብዎን 150 ቃላት ውስጥ ያስቀርቡ።',
  business_goals: 'እባክዎ የንግድ ግብዣዎችን 100 ቃላት ውስጥ ያስቀርቡ።',
  market_overview: 'እባክዎ ተጨማሪ ዝርዝር ያብርቱ።',
  product_service_1: 'እባክዎ ዋናው ምርት/አገልግሎትን ያብርቱ።',
  market_served_1: 'እባክዎ ማርኬቱን ያብርቱ (አካባቢው፣ ብሔራዊ፣ ዓለም አቀፍ)።',
  distribution_channels_1: 'እባክዎ የማከማቻ አካባቢዎችን ያብርቱ።',
  product_service_uniqueness: 'ምን ያስፈልጋል ያለ አካል ነው?',
  raw_material_sourcing_pct: 'እባክዎ ከ 0 እስከ 100 የሚሆን በመቶ ያብርቱ።',
  management_name_1: 'እባክዎ የአስተዳደር ቡድን አባል ስም ያብርቱ።',
  management_position_1: 'እባክዎ ሚናውን ያብርቱ።',
  management_gender_1: 'እባክዎ ፆታውን ያብርቱ (ወንድ/ሴት/ሌላ)።',
  problem_to_be_addressed: 'እባክዎ የተወሰነ ሽታን ያብርቱ።',
  machinery_description_1: 'እባክዎ የሚጠየቁትን ዕቃ ያብርቱ።',
  machinery_quantity_1: 'እባክዎ ቁጥር ያብርቱ።',
  machinery_price_1: 'እባክዎ የሚጠበቀውን ጠቅላላ ዋጋ በኢትብ ያብርቱ።',
  machinery_purpose_1: 'እባክዎ የዚህ ዕቃን ለምን እንደሚጠቀም ያብርቱ።',
  consultant_problem_1: 'እባክዎ የሚያስፈልገውን ሽታ ያብርቱ።',
  consultant_expertise_1: 'እባክዎ የሚጠየቀውን ቴክኒካል እባክነት ያብርቱ።',
  expected_results: 'እባክዎ የሚጠበቁትን ውጤቶች ያብርቱ።',
  priority_area_1: 'እባክዎ ዕቃዎች/እባክነት ውጤቶችን እንዴት ነው የሚፈጽሙ ያብርቱ።',
  priority_area_2: 'እባክዎ ዕቃዎች/እባክነት ውጤቶችን እንዴት ነው የሚፈጽሙ ያብርቱ።',
  priority_area_3: 'እባክዎ ዕቃዎች/እባክነት ውጤቶችን እንዴት ነው የሚፈጽሙ ያብርቱ።',
  job_creation_explanation: 'እባክዎ የሰራተኞች ቁጥር እና ምክንያቱን ያብርቱ።',
  job_position_1: 'እባክዎ የሰራተኛ ሚናውን ያብርቱ።',
  job_count_1: 'እባክዎ የአዲስ ሰራተኞች ቁጥር ያብርቱ።',
  social_env_impact_osh: 'እባክዎ 100 ቃላት ውስጥ ያስቀርቡ።',
  osh_standards: 'እባክዎ 100 ቃላት ውስጥ ያስቀርቡ።',
};

const followUpOm: Record<string, string> = {
  company_name: 'Maqaa kaampaaniyaa keessanii deebi\'u dandeessa?',
  business_registration_number: 'Lakkoofsi galmeen bakka buusuu dha. Lakkoofsi guutuu kenneessaa?',
  address: 'Magaalaa fi kilil keessatti teessoo guutuu kennuu danda\'a?',
  mobile_number: '+251 ittis jiraacha bilbilaa sirrii Oromiyaa kennuu danda\'a?',
  business_organization_form: 'Ibsi: Kan of eegaa, kan biroo gahaa, kan akishiyoonii, knoo waliin.',
  years_in_operation: 'Waggaa lakkoofsaa kennuu danda\'a?',
  business_type: 'Qabaa keessan ibsi (fkn: eeggii, lika, tajaajila, cinii, hojii qotee).',
  ownership_percentage_women: 'Saasa 0-100 irratti kennuu danda\'a?',
  ownership_percentage_men: 'Saasa 0-100 irratti kennuu danda\'a. Dubartoonni saasa waliin 100% ta\'u danda\'a.',
  development_since_start: 'Dandaama daldalaa keessan ogeessa kennuu danda\'a?',
  motivation_to_apply: 'Barbaaddaa kee saasa 150 irratti qabaatuu danda\'a?',
  business_goals: 'Kaayyoo daldalaa keessan saasa 100 irratti qabaatuu danda\'a?',
  market_overview: 'Garaagaraa daldalaa keessan ogeessa kennuu danda\'a?',
  product_service_1: 'Mootummaa/tajaajila guddaa deeggarsa.',
  market_served_1: 'Gara garaagaraa eessa? (biyyessa, tokkicha, iddoo)',
  distribution_channels_1: 'Kaayyoo gurgurtoo deeggarsa.',
  product_service_uniqueness: 'Maaliif qabxii qaba?',
  raw_material_sourcing_pct: 'Saasa 0-100 irratti kennuu danda\'a?',
  management_name_1: 'Maqaa lammaa hojii maatii kennuu danda\'a?',
  management_position_1: 'Hojii isaa maali?',
  management_gender_1: 'Saala isaa maali? (Dhiira/Dubartii/Birayyoo)',
  problem_to_be_addressed: 'Rakkachii qabxii ibsi.',
  machinery_description_1: 'Meeshaa barbaachisaa ibsi.',
  machinery_quantity_1: 'Lakkoofsaa kennuu danda\'a?',
  machinery_price_1: 'Qimmii waliigalaa ETB irratti kennuu danda\'a?',
  machinery_purpose_1: 'Kun meeshaa maaliif barbaadu?',
  consultant_problem_1: 'Rakkachii teknikoolaa barbaachisaa qaba ibsi.',
  consultant_expertise_1: 'Barbaachisa teknikoolaa meeqa qabate ibsi.',
  expected_results: 'Gaariiwwan kan tarree jira ibsi.',
  priority_area_1: 'Meeshaalee/barbaachisaa gaariiwwan akka danda\'amuuf dandaa\'u?',
  priority_area_2: 'Meeshaalee/barbaachisaa gaariiwwan akka danda\'amuuf dandaa\'u?',
  priority_area_3: 'Meeshaalee/barbaachisaa gaariiwwan akka danda\'amuuf dandaa\'u?',
  job_creation_explanation: 'Hojjettoota haaraa fi ibsaa isaa kennuu danda\'a?',
  job_position_1: 'Hojii maali?',
  job_count_1: 'Lakkoofsaa hojjettoota haaraa kennuu danda\'a?',
  social_env_impact_osh: 'Saasa 100 irratti qabaatuu danda\'a?',
  osh_standards: 'Saasa 100 irratti qabaatuu danda\'a?',
};

export const coverageMap: FieldDefinition[] = [
  // Section 1.1 Company Profile
  {
    id: 'company_name',
    required: true,
    priority: 1,
    question: { en: en.company_name, am: am.company_name, om: om.company_name },
    followUpQuestion: { en: followUpEn.company_name, am: followUpAm.company_name, om: followUpOm.company_name },
  },
  {
    id: 'business_registration_number',
    required: true,
    priority: 2,
    question: { en: en.business_registration_number, am: am.business_registration_number, om: om.business_registration_number },
    followUpQuestion: { en: followUpEn.business_registration_number, am: followUpAm.business_registration_number, om: followUpOm.business_registration_number },
  },
  {
    id: 'address',
    required: true,
    priority: 3,
    question: { en: en.address, am: am.address, om: om.address },
    followUpQuestion: { en: followUpEn.address, am: followUpAm.address, om: followUpOm.address },
  },
  {
    id: 'mobile_number',
    required: true,
    priority: 4,
    question: { en: en.mobile_number, am: am.mobile_number, om: om.mobile_number },
    followUpQuestion: { en: followUpEn.mobile_number, am: followUpAm.mobile_number, om: followUpOm.mobile_number },
  },
  {
    id: 'email',
    required: false,
    priority: 5,
    question: { en: en.email, am: am.email, om: om.email },
    followUpQuestion: { en: followUpEn.email, am: followUpAm.email, om: followUpOm.email },
  },
  {
    id: 'business_organization_form',
    required: true,
    priority: 6,
    question: { en: en.business_organization_form, am: am.business_organization_form, om: om.business_organization_form },
    followUpQuestion: { en: followUpEn.business_organization_form, am: followUpAm.business_organization_form, om: followUpOm.business_organization_form },
  },
  {
    id: 'years_in_operation',
    required: true,
    priority: 7,
    question: { en: en.years_in_operation, am: am.years_in_operation, om: om.years_in_operation },
    followUpQuestion: { en: followUpEn.years_in_operation, am: followUpAm.years_in_operation, om: followUpOm.years_in_operation },
  },
  {
    id: 'business_type',
    required: true,
    priority: 8,
    question: { en: en.business_type, am: am.business_type, om: om.business_type },
    followUpQuestion: { en: followUpEn.business_type, am: followUpAm.business_type, om: followUpOm.business_type },
  },
  {
    id: 'ownership_percentage_women',
    required: true,
    priority: 9,
    question: { en: en.ownership_percentage_women, am: am.ownership_percentage_women, om: om.ownership_percentage_women },
    followUpQuestion: { en: followUpEn.ownership_percentage_women, am: followUpAm.ownership_percentage_women, om: followUpOm.ownership_percentage_women },
  },
  {
    id: 'ownership_percentage_men',
    required: true,
    priority: 10,
    question: { en: en.ownership_percentage_men, am: am.ownership_percentage_men, om: om.ownership_percentage_men },
    followUpQuestion: { en: followUpEn.ownership_percentage_men, am: followUpAm.ownership_percentage_men, om: followUpOm.ownership_percentage_men },
  },
  // Section 1.2 Company Overview
  {
    id: 'development_since_start',
    required: true,
    priority: 11,
    question: { en: en.development_since_start, am: am.development_since_start, om: om.development_since_start },
    followUpQuestion: { en: followUpEn.development_since_start, am: followUpAm.development_since_start, om: followUpOm.development_since_start },
  },
  {
    id: 'motivation_to_apply',
    required: true,
    priority: 12,
    question: { en: en.motivation_to_apply, am: am.motivation_to_apply, om: om.motivation_to_apply },
    followUpQuestion: { en: followUpEn.motivation_to_apply, am: followUpAm.motivation_to_apply, om: followUpOm.motivation_to_apply },
  },
  {
    id: 'business_goals',
    required: true,
    priority: 13,
    question: { en: en.business_goals, am: am.business_goals, om: om.business_goals },
    followUpQuestion: { en: followUpEn.business_goals, am: followUpAm.business_goals, om: followUpOm.business_goals },
  },
  {
    id: 'market_overview',
    required: true,
    priority: 14,
    question: { en: en.market_overview, am: am.market_overview, om: om.market_overview },
    followUpQuestion: { en: followUpEn.market_overview, am: followUpAm.market_overview, om: followUpOm.market_overview },
  },
  {
    id: 'product_service_1',
    required: true,
    priority: 15,
    question: { en: en.product_service_1, am: am.product_service_1, om: om.product_service_1 },
    followUpQuestion: { en: followUpEn.product_service_1, am: followUpAm.product_service_1, om: followUpOm.product_service_1 },
  },
  {
    id: 'market_served_1',
    required: true,
    priority: 16,
    question: { en: en.market_served_1, am: am.market_served_1, om: om.market_served_1 },
    followUpQuestion: { en: followUpEn.market_served_1, am: followUpAm.market_served_1, om: followUpOm.market_served_1 },
  },
  {
    id: 'distribution_channels_1',
    required: true,
    priority: 17,
    question: { en: en.distribution_channels_1, am: am.distribution_channels_1, om: om.distribution_channels_1 },
    followUpQuestion: { en: followUpEn.distribution_channels_1, am: followUpAm.distribution_channels_1, om: followUpOm.distribution_channels_1 },
  },
  {
    id: 'product_service_uniqueness',
    required: true,
    priority: 18,
    question: { en: en.product_service_uniqueness, am: am.product_service_uniqueness, om: om.product_service_uniqueness },
    followUpQuestion: { en: followUpEn.product_service_uniqueness, am: followUpAm.product_service_uniqueness, om: followUpOm.product_service_uniqueness },
  },
  {
    id: 'raw_material_sourcing_pct',
    required: false,
    priority: 19,
    question: { en: en.raw_material_sourcing_pct, am: am.raw_material_sourcing_pct, om: om.raw_material_sourcing_pct },
    followUpQuestion: { en: followUpEn.raw_material_sourcing_pct, am: followUpAm.raw_material_sourcing_pct, om: followUpOm.raw_material_sourcing_pct },
  },
  // Section 1.8 Management Structure
  {
    id: 'management_name_1',
    required: true,
    priority: 20,
    question: { en: en.management_name_1, am: am.management_name_1, om: om.management_name_1 },
    followUpQuestion: { en: followUpEn.management_name_1, am: followUpAm.management_name_1, om: followUpOm.management_name_1 },
  },
  {
    id: 'management_position_1',
    required: true,
    priority: 21,
    question: { en: en.management_position_1, am: am.management_position_1, om: om.management_position_1 },
    followUpQuestion: { en: followUpEn.management_position_1, am: followUpAm.management_position_1, om: followUpOm.management_position_1 },
  },
  {
    id: 'management_gender_1',
    required: true,
    priority: 22,
    question: { en: en.management_gender_1, am: am.management_gender_1, om: om.management_gender_1 },
    followUpQuestion: { en: followUpEn.management_gender_1, am: followUpAm.management_gender_1, om: followUpOm.management_gender_1 },
  },
  // Section 2.1
  {
    id: 'problem_to_be_addressed',
    required: true,
    priority: 23,
    question: { en: en.problem_to_be_addressed, am: am.problem_to_be_addressed, om: om.problem_to_be_addressed },
    followUpQuestion: { en: followUpEn.problem_to_be_addressed, am: followUpAm.problem_to_be_addressed, om: followUpOm.problem_to_be_addressed },
  },
  // Section 2.2 Machinery
  {
    id: 'machinery_description_1',
    required: true,
    priority: 24,
    question: { en: en.machinery_description_1, am: am.machinery_description_1, om: om.machinery_description_1 },
    followUpQuestion: { en: followUpEn.machinery_description_1, am: followUpAm.machinery_description_1, om: followUpOm.machinery_description_1 },
  },
  {
    id: 'machinery_quantity_1',
    required: true,
    priority: 25,
    question: { en: en.machinery_quantity_1, am: am.machinery_quantity_1, om: om.machinery_quantity_1 },
    followUpQuestion: { en: followUpEn.machinery_quantity_1, am: followUpAm.machinery_quantity_1, om: followUpOm.machinery_quantity_1 },
  },
  {
    id: 'machinery_price_1',
    required: true,
    priority: 26,
    question: { en: en.machinery_price_1, am: am.machinery_price_1, om: om.machinery_price_1 },
    followUpQuestion: { en: followUpEn.machinery_price_1, am: followUpAm.machinery_price_1, om: followUpOm.machinery_price_1 },
  },
  {
    id: 'machinery_purpose_1',
    required: true,
    priority: 27,
    question: { en: en.machinery_purpose_1, am: am.machinery_purpose_1, om: om.machinery_purpose_1 },
    followUpQuestion: { en: followUpEn.machinery_purpose_1, am: followUpAm.machinery_purpose_1, om: followUpOm.machinery_purpose_1 },
  },
  // Section 2.3 Consultants
  {
    id: 'consultant_problem_1',
    required: true,
    priority: 28,
    question: { en: en.consultant_problem_1, am: am.consultant_problem_1, om: om.consultant_problem_1 },
    followUpQuestion: { en: followUpEn.consultant_problem_1, am: followUpAm.consultant_problem_1, om: followUpOm.consultant_problem_1 },
  },
  {
    id: 'consultant_expertise_1',
    required: true,
    priority: 29,
    question: { en: en.consultant_expertise_1, am: am.consultant_expertise_1, om: om.consultant_expertise_1 },
    followUpQuestion: { en: followUpEn.consultant_expertise_1, am: followUpAm.consultant_expertise_1, om: followUpOm.consultant_expertise_1 },
  },
  // Section 2.4 Expected Results
  {
    id: 'expected_results',
    required: true,
    priority: 30,
    question: { en: en.expected_results, am: am.expected_results, om: om.expected_results },
    followUpQuestion: { en: followUpEn.expected_results, am: followUpAm.expected_results, om: followUpOm.expected_results },
  },
  {
    id: 'priority_area_1',
    required: true,
    priority: 31,
    question: { en: en.priority_area_1, am: am.priority_area_1, om: om.priority_area_1 },
    followUpQuestion: { en: followUpEn.priority_area_1, am: followUpAm.priority_area_1, om: followUpOm.priority_area_1 },
  },
  {
    id: 'priority_area_2',
    required: true,
    priority: 32,
    question: { en: en.priority_area_2, am: am.priority_area_2, om: om.priority_area_2 },
    followUpQuestion: { en: followUpEn.priority_area_2, am: followUpAm.priority_area_2, om: followUpOm.priority_area_2 },
  },
  {
    id: 'priority_area_3',
    required: true,
    priority: 33,
    question: { en: en.priority_area_3, am: am.priority_area_3, om: om.priority_area_3 },
    followUpQuestion: { en: followUpEn.priority_area_3, am: followUpAm.priority_area_3, om: followUpOm.priority_area_3 },
  },
  // Section 2.5 Job Creation
  {
    id: 'job_creation_explanation',
    required: true,
    priority: 34,
    question: { en: en.job_creation_explanation, am: am.job_creation_explanation, om: om.job_creation_explanation },
    followUpQuestion: { en: followUpEn.job_creation_explanation, am: followUpAm.job_creation_explanation, om: followUpOm.job_creation_explanation },
  },
  {
    id: 'job_position_1',
    required: true,
    priority: 35,
    question: { en: en.job_position_1, am: am.job_position_1, om: om.job_position_1 },
    followUpQuestion: { en: followUpEn.job_position_1, am: followUpAm.job_position_1, om: followUpOm.job_position_1 },
  },
  {
    id: 'job_count_1',
    required: true,
    priority: 36,
    question: { en: en.job_count_1, am: am.job_count_1, om: om.job_count_1 },
    followUpQuestion: { en: followUpEn.job_count_1, am: followUpAm.job_count_1, om: followUpOm.job_count_1 },
  },
  // Section 2.6/2.7
  {
    id: 'social_env_impact_osh',
    required: true,
    priority: 37,
    question: { en: en.social_env_impact_osh, am: am.social_env_impact_osh, om: om.social_env_impact_osh },
    followUpQuestion: { en: followUpEn.social_env_impact_osh, am: followUpAm.social_env_impact_osh, om: followUpOm.social_env_impact_osh },
  },
  {
    id: 'osh_standards',
    required: true,
    priority: 38,
    question: { en: en.osh_standards, am: am.osh_standards, om: om.osh_standards },
    followUpQuestion: { en: followUpEn.osh_standards, am: followUpAm.osh_standards, om: followUpOm.osh_standards },
  },
];

// Growth Indicators Table (handled separately as structured data)
export const growthIndicatorFields = {
  sales_etb: ['2022', '2023', '2024', '2025_projection', '2026_projection'],
  total_employees: ['2022', '2023', '2024', '2025_projection', '2026_projection'],
  female_employees: ['2022', '2023', '2024', '2025_projection', '2026_projection'],
  youth_employees_18_24: ['2022', '2023', '2024', '2025_projection', '2026_projection'],
};

export const languageNames: Record<Language, string> = {
  en: 'English',
  am: 'Amharic',
  om: 'Afaan Oromo',
};

export const languageNativeNames: Record<Language, string> = {
  en: 'English',
  am: 'አማርኛ',
  om: 'Afaan Oromoo',
};