import { ReviewerFixture } from './types';

export const reviewerFixtures: ReviewerFixture[] = [
  {
    id: 'app-001',
    channel: 'web',
    synthetic: true,
    input: {
      sales_growth_pct: 60,
      total_employees: 25,
      uniqueness: 'new_in_ethiopia',
      market_served: 'international',
      local_sourcing_pct: 80,
      ownership: 'women_owned',
      women_employee_pct: 60,
      youth_employee_pct: 55,
      expected_results_count: 3,
      job_count: 450,
      investment_readiness: 30,
      management_team_size: 4,
      impact_category: 'green_business_model',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-002',
    channel: 'telegram',
    synthetic: true,
    input: {
      sales_growth_pct: 40,
      total_employees: 15,
      uniqueness: 'different_from_competitors',
      market_served: 'import_substituting',
      local_sourcing_pct: 50,
      ownership: 'women_managed',
      women_employee_pct: 45,
      youth_employee_pct: 30,
      expected_results_count: 2,
      job_count: 250,
      investment_readiness: 22,
      management_team_size: 3,
      impact_category: 'both_social_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-003',
    channel: 'web',
    synthetic: true,
    input: {
      sales_growth_pct: 20,
      total_employees: 8,
      uniqueness: 'essential',
      market_served: 'local_only',
      local_sourcing_pct: 30,
      ownership: 'neither',
      women_employee_pct: 20,
      youth_employee_pct: 15,
      expected_results_count: 1,
      job_count: 150,
      investment_readiness: 18,
      management_team_size: 2,
      impact_category: 'either_social_or_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
    incompleteFields: ['job_count'],
  },
  {
    id: 'app-004',
    channel: 'telegram',
    synthetic: true,
    input: {
      sales_growth_pct: 10,
      total_employees: 4,
      uniqueness: 'no_unique',
      market_served: 'local_only',
      local_sourcing_pct: 10,
      ownership: 'neither',
      women_employee_pct: 5,
      youth_employee_pct: 5,
      expected_results_count: 1,
      job_count: 50,
      investment_readiness: 10,
      management_team_size: 1,
      impact_category: 'neither',
      legally_registered_and_years: false,
      privately_owned: true,
    },
  },
  {
    id: 'app-005',
    channel: 'web',
    synthetic: true,
    input: {
      sales_growth_pct: 55,
      total_employees: 30,
      uniqueness: 'new_in_ethiopia',
      market_served: 'international',
      local_sourcing_pct: 70,
      ownership: 'women_owned',
      women_employee_pct: 70,
      youth_employee_pct: 60,
      expected_results_count: 3,
      job_count: 500,
      investment_readiness: 35,
      management_team_size: 5,
      impact_category: 'green_business_model',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-006',
    channel: 'telegram',
    synthetic: true,
    input: {
      sales_growth_pct: 45,
      total_employees: 20,
      uniqueness: 'different_from_competitors',
      market_served: 'import_substituting',
      local_sourcing_pct: 60,
      ownership: 'women_managed',
      women_employee_pct: 50,
      youth_employee_pct: 40,
      expected_results_count: 3,
      job_count: 350,
      investment_readiness: 28,
      management_team_size: 4,
      impact_category: 'both_social_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-007',
    channel: 'web',
    synthetic: true,
    input: {
      sales_growth_pct: 30,
      total_employees: 12,
      uniqueness: 'essential',
      market_served: 'local_only',
      local_sourcing_pct: 40,
      ownership: 'neither',
      women_employee_pct: 25,
      youth_employee_pct: 20,
      expected_results_count: 2,
      job_count: 200,
      investment_readiness: 20,
      management_team_size: 3,
      impact_category: 'either_social_or_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-008',
    channel: 'telegram',
    synthetic: true,
    input: {
      sales_growth_pct: 70,
      total_employees: 40,
      uniqueness: 'new_in_ethiopia',
      market_served: 'international',
      local_sourcing_pct: 90,
      ownership: 'women_owned',
      women_employee_pct: 80,
      youth_employee_pct: 70,
      expected_results_count: 3,
      job_count: 600,
      investment_readiness: 40,
      management_team_size: 6,
      impact_category: 'green_business_model',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-009',
    channel: 'web',
    synthetic: true,
    input: {
      sales_growth_pct: 15,
      total_employees: 6,
      uniqueness: 'no_unique',
      market_served: 'local_only',
      local_sourcing_pct: 15,
      ownership: 'neither',
      women_employee_pct: 10,
      youth_employee_pct: 10,
      expected_results_count: 1,
      job_count: 100,
      investment_readiness: 12,
      management_team_size: 2,
      impact_category: 'neither',
      legally_registered_and_years: true,
      privately_owned: false,
    },
  },
  {
    id: 'app-010',
    channel: 'telegram',
    synthetic: true,
    input: {
      sales_growth_pct: 50,
      total_employees: 22,
      uniqueness: 'different_from_competitors',
      market_served: 'import_substituting',
      local_sourcing_pct: 55,
      ownership: 'women_managed',
      women_employee_pct: 55,
      youth_employee_pct: 45,
      expected_results_count: 2,
      job_count: 320,
      investment_readiness: 25,
      management_team_size: 4,
      impact_category: 'both_social_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
    contradiction: 'License issue date suggests company is newer than claimed years in operation.',
  },
  {
    id: 'app-011',
    channel: 'web',
    synthetic: true,
    input: {
      sales_growth_pct: 25,
      total_employees: 10,
      uniqueness: 'essential',
      market_served: 'local_only',
      local_sourcing_pct: 35,
      ownership: 'neither',
      women_employee_pct: 20,
      youth_employee_pct: 15,
      expected_results_count: 1,
      job_count: 180,
      investment_readiness: 16,
      management_team_size: 2,
      impact_category: 'either_social_or_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-012',
    channel: 'telegram',
    synthetic: true,
    input: {
      sales_growth_pct: 65,
      total_employees: 35,
      uniqueness: 'new_in_ethiopia',
      market_served: 'international',
      local_sourcing_pct: 85,
      ownership: 'women_owned',
      women_employee_pct: 75,
      youth_employee_pct: 65,
      expected_results_count: 3,
      job_count: 550,
      investment_readiness: 38,
      management_team_size: 5,
      impact_category: 'green_business_model',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
];