import { ScoringInput } from '../rules/types';

export interface ReviewerFixture {
  id: string;
  channel: 'web' | 'telegram';
  synthetic: boolean;
  input: ScoringInput;
  contradiction?: string;
  incompleteFields?: string[];
}

export interface RankedApplication {
  id: string;
  channel: 'web' | 'telegram';
  synthetic: boolean;
  eligible: boolean;
  eligibilityStatus: 'eligible' | 'ineligible' | 'needs_review';
  exclusions: any[];
  criterionScores: any[];
  totalPointsVariantA: number;
  totalPointsVariantB: number;
  reviewFlags: string[];
  contradiction?: string;
  incompleteFields?: string[];
  rank?: number;
  c7VariantUsed?: 'C7a' | 'C7b';
}

export const reviewerFixtures: ReviewerFixture[] = [
  {
    id: 'app-001',
    channel: 'web',
    synthetic: true,
    input: {
      sales_growth_pct: 65,
      total_employees: 28,
      uniqueness: 'new_in_ethiopia',
      market_served: 'international',
      local_sourcing_pct: 85,
      ownership: 'women_owned',
      women_employee_pct: 62,
      youth_employee_pct: 58,
      expected_results_count: 3,
      job_count: 480,
      investment_readiness: 32,
      management_team_size: 5,
      impact_category: 'green_business_model',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-002',
    channel: 'telegram',
    synthetic: true,
    input: {
      sales_growth_pct: 42,
      total_employees: 18,
      uniqueness: 'different_from_competitors',
      market_served: 'import_substituting',
      local_sourcing_pct: 55,
      ownership: 'women_managed',
      women_employee_pct: 48,
      youth_employee_pct: 35,
      expected_results_count: 2,
      job_count: 280,
      investment_readiness: 24,
      management_team_size: 3,
      impact_category: 'both_social_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-003',
    channel: 'web',
    synthetic: true,
    input: {
      sales_growth_pct: 18,
      total_employees: 6,
      uniqueness: 'essential',
      market_served: 'local_only',
      local_sourcing_pct: 28,
      ownership: 'neither',
      women_employee_pct: 15,
      youth_employee_pct: 12,
      expected_results_count: 1,
      job_count: 140,
      investment_readiness: 17,
      management_team_size: 2,
      impact_category: 'either_social_or_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
    incompleteFields: ['job_count'],
  },
  {
    id: 'app-004',
    channel: 'telegram',
    synthetic: true,
    input: {
      sales_growth_pct: 8,
      total_employees: 3,
      uniqueness: 'no_unique',
      market_served: 'local_only',
      local_sourcing_pct: 8,
      ownership: 'neither',
      women_employee_pct: 3,
      youth_employee_pct: 4,
      expected_results_count: 1,
      job_count: 45,
      investment_readiness: 8,
      management_team_size: 1,
      impact_category: 'neither',
      legally_registered_and_years: false,
      privately_owned: true,
    },
  },
  {
    id: 'app-005',
    channel: 'web',
    synthetic: true,
    input: {
      sales_growth_pct: 58,
      total_employees: 32,
      uniqueness: 'new_in_ethiopia',
      market_served: 'international',
      local_sourcing_pct: 75,
      ownership: 'women_owned',
      women_employee_pct: 72,
      youth_employee_pct: 65,
      expected_results_count: 3,
      job_count: 520,
      investment_readiness: 38,
      management_team_size: 6,
      impact_category: 'green_business_model',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-006',
    channel: 'telegram',
    synthetic: true,
    input: {
      sales_growth_pct: 48,
      total_employees: 22,
      uniqueness: 'different_from_competitors',
      market_served: 'import_substituting',
      local_sourcing_pct: 65,
      ownership: 'women_managed',
      women_employee_pct: 52,
      youth_employee_pct: 42,
      expected_results_count: 3,
      job_count: 380,
      investment_readiness: 30,
      management_team_size: 4,
      impact_category: 'both_social_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-007',
    channel: 'web',
    synthetic: true,
    input: {
      sales_growth_pct: 32,
      total_employees: 14,
      uniqueness: 'essential',
      market_served: 'local_only',
      local_sourcing_pct: 42,
      ownership: 'neither',
      women_employee_pct: 28,
      youth_employee_pct: 22,
      expected_results_count: 2,
      job_count: 220,
      investment_readiness: 22,
      management_team_size: 3,
      impact_category: 'either_social_or_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-008',
    channel: 'telegram',
    synthetic: true,
    input: {
      sales_growth_pct: 72,
      total_employees: 45,
      uniqueness: 'new_in_ethiopia',
      market_served: 'international',
      local_sourcing_pct: 92,
      ownership: 'women_owned',
      women_employee_pct: 82,
      youth_employee_pct: 75,
      expected_results_count: 3,
      job_count: 650,
      investment_readiness: 42,
      management_team_size: 7,
      impact_category: 'green_business_model',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-009',
    channel: 'web',
    synthetic: true,
    input: {
      sales_growth_pct: 12,
      total_employees: 5,
      uniqueness: 'no_unique',
      market_served: 'local_only',
      local_sourcing_pct: 12,
      ownership: 'neither',
      women_employee_pct: 8,
      youth_employee_pct: 8,
      expected_results_count: 1,
      job_count: 80,
      investment_readiness: 10,
      management_team_size: 2,
      impact_category: 'neither',
      legally_registered_and_years: true,
      privately_owned: false,
    },
  },
  {
    id: 'app-010',
    channel: 'telegram',
    synthetic: true,
    input: {
      sales_growth_pct: 52,
      total_employees: 25,
      uniqueness: 'different_from_competitors',
      market_served: 'import_substituting',
      local_sourcing_pct: 58,
      ownership: 'women_managed',
      women_employee_pct: 58,
      youth_employee_pct: 48,
      expected_results_count: 2,
      job_count: 340,
      investment_readiness: 28,
      management_team_size: 4,
      impact_category: 'both_social_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
    contradiction: 'License issue date suggests company is newer than claimed years in operation.',
  },
  {
    id: 'app-011',
    channel: 'web',
    synthetic: true,
    input: {
      sales_growth_pct: 28,
      total_employees: 11,
      uniqueness: 'essential',
      market_served: 'local_only',
      local_sourcing_pct: 38,
      ownership: 'neither',
      women_employee_pct: 22,
      youth_employee_pct: 18,
      expected_results_count: 1,
      job_count: 190,
      investment_readiness: 18,
      management_team_size: 2,
      impact_category: 'either_social_or_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-012',
    channel: 'telegram',
    synthetic: true,
    input: {
      sales_growth_pct: 68,
      total_employees: 38,
      uniqueness: 'new_in_ethiopia',
      market_served: 'international',
      local_sourcing_pct: 88,
      ownership: 'women_owned',
      women_employee_pct: 78,
      youth_employee_pct: 68,
      expected_results_count: 3,
      job_count: 580,
      investment_readiness: 40,
      management_team_size: 5,
      impact_category: 'green_business_model',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
];